---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: benefits
  labels:
    app: benefits
spec:
  replicas: 2
  selector:
    matchLabels:
      app: benefits
  template:
    metadata:
      labels:
        app: benefits
    spec:
      containers:
      - name: benefits-wls
        image: markfjohnson/wls_benefits_k8s
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: benefits
spec:
  selector:
    app: benefits
  ports:
    - port: 80
      targetPort: 10100