apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: kube-system
stringData:
  key_id: "ASIARTOCEFOGXMV5P5E3"
  access_key: "AE8O/Vj/gkPHYbBmDqDF3ofs7Bo5by+mUF3vFBBb"
  session_token: "FQoGZXIvYXdzEBgaDGdbHeiShhNvMMl50CL7AQ2sRkJw51HJSzCAFJzPP3jWvwvwi7ODO03e2HRa7G7yc9ZOqAxI3jlTDJvRC5mQmapiPJWqkpM9ufRhM23jqyp/EgxZArarN23tGfCd62Gb3u+3TFbrVjHXaGcb8I2MtXT3mrFhF4y/smyeiolwNJ1K+uF1rsC7B8egkBHrua4NwnVcd/Aw8veYe2fw3xRlT0G0aP7lpRLnZPBvJl/o9mq/1NFdn64/VMgwiATQKDxJnGCcBAOryjQL7DtNiHwNieyy4ML01p/h+HhIxFwSqGMhNls36FCi6MZTkfZjPpGgVqdb321gAL3x0R+X3FvJDtBcasPTijgTaJPuKPCdieIF"
